In [2]:
import tensorflow as tf
import numpy as np

# Graph & Session

In [3]:
# numpy array
a = np.array([1,2,3])
b = np.array([2,4,6])
c = np.add(a,b)
print(c)

[3 6 9]


### constant

In [4]:

# tensor - no immediate evaluation
x = tf.constant([1,2,3], name="x")
y = tf.constant([2,4,6], name="y")
z = tf.add(x,y) # no calculation happens at this line
print(z)


Tensor("Add:0", shape=(3,), dtype=int32)


In [4]:
# session.run
with tf.Session() as sess:
    result = sess.run(z) # a sess comes with a graph
    result = z.eval()
    print(result) # calculation happens here!
    
#    writer = tf.summary.FileWriter('./lab1_graph_and_session', sess.graph)
#writer.close()

[3 6 9]


# Variable & Placeholder

## variable

In [5]:
# Variable

state = tf.Variable(0, name = 'counter') #a Variable init as 0, named as counter
current = tf.add(state, 1) # an operator:add 1 to the variable:state

update = tf.assign(state, current) #state <- current

#Note: Always remember to init operator if using Variable
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(state)) # print init value
    
    for _ in range(5):
        sess.run(update)
        print(sess.run(state)) 

0
1
2
3
4
5


In [6]:
# Variable

with tf.variable_scope("model", reuse=tf.AUTO_REUSE):
    w = tf.get_variable("weight", 
                       shape=(1,2),
                       initializer=tf.truncated_normal_initializer(),
                       trainable=True)
    
    print(w)
    
    with tf.Session() as sess:
        tf.global_variables_initializer().run()
        for _ in range(3):
            out = tf.add(w, 1)
            w = w + 0.1
            print('Loop {}'.format(_))
            print(sess.run(out))
            # TH: Try this
            #print(out.eval())

<tf.Variable 'model/weight:0' shape=(1, 2) dtype=float32_ref>
Loop 0
[[0.2840466  0.47179484]]
Loop 1
[[0.3840466  0.57179487]]
Loop 2
[[0.48404664 0.6717949 ]]


## placeholder

In [6]:
# Placeholder

p1 = tf.placeholder("float", None)
p2 = p1 * 2

print(p1)

with tf.Session() as sess:
    print(sess.run(p2, feed_dict={p1: [[1.1,2.2,3.3],[2,4,6]]}))

Tensor("Placeholder:0", dtype=float32)
[[ 2.2  4.4  6.6]
 [ 4.   8.  12. ]]


# Tensor
## multi dimensionial array of data

In [7]:
x0 = tf.constant(3)
x1 = tf.constant([1,3,5])
x2 = tf.stack([x1,x1])
x3 = tf.stack([x2,x2,x2,x2])
x4 = tf.stack([x3,x3])

In [8]:
print(x0)
print(x1)
print(x2)
print(x3)
print(x4)

Tensor("Const:0", shape=(), dtype=int32)
Tensor("Const_1:0", shape=(3,), dtype=int32)
Tensor("stack:0", shape=(2, 3), dtype=int32)
Tensor("stack_1:0", shape=(4, 2, 3), dtype=int32)
Tensor("stack_2:0", shape=(2, 4, 2, 3), dtype=int32)


## slicing a tensor

In [9]:
y = x2[1,0:2]

# TH: Try this
#y = x2[1,0:2]

with tf.Session() as sess:
    print(y.eval())

[1 3]


## reshape

In [11]:
x = tf.constant([[1,3,5],
                 [2,4,6]])

y = tf.reshape(x,[3,2])

y2 = tf.reshape(x,[3,2])[1,:]

with tf.Session() as sess:
    print(y.eval())
    print(y2.eval())

[[1 3]
 [5 2]
 [4 6]]
[5 2]


# TensorBoard

In [12]:
a, b, c, d = tf.constant(1), tf.constant(2), tf.constant(3),tf.constant(4)

add = tf.add(a,b)
mul = tf.multiply(add, c)
sub = tf.subtract(mul, d)

# TH: Try this
add = a + b
mul = add * c
sub = mul - d

with tf.Session() as sess:
    
    fwrite = tf.summary.FileWriter('./lab1_tensorboard', sess.graph)
    
    print(sess.run(sub))
fwrite.close()

5


### How to open TensorBoard?

1. At cmd prompt, run 

`tensorboard --logdir=/path/to/dir`

2. At browser, go to http://localhost:6006

For info: https://github.com/tensorflow/tensorboard/blob/master/README.md